version: 2.1

orbs:
  docker: circleci/docker@1.7.0

jobs:
  dev-job:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - setup_remote_docker
      - docker/build:
          registry: registry.thinx.cloud:5000
          docker-context: ./dev
          image: thinxcloud/console-build-env
          dockerfile: ./dev/Dockerfile
          tag: 'latest'
      - docker/push:
          digest-path: /tmp/digest.txt
          image: thinxcloud/console-build-env
          registry: registry.thinx.cloud:5000
          tag: 'latest'

  vue-job:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - setup_remote_docker
      - docker/build:
          #registry: registry.thinx.cloud:5000
          docker-context: ./vue
          image: thinxcloud/console-build-env
          dockerfile: ./vue/Dockerfile
          tag: 'vue'
      - docker/push:
          digest-path: /tmp/digest.txt
          image: thinxcloud/console-build-env
          #registry: registry.thinx.cloud:5000
          tag: 'vue'

workflows:
  build-dev:
    jobs:
      - dev-job
  build-vue:
    jobs:
      - vue-job
