version: 2.1

orbs:
  docker: circleci/docker@1.7.0

jobs:
  dev-job:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - setup_remote_docker
      - docker/check
      - docker/build:
          docker-context: ./dev
          image: suculent/console-build-env
          dockerfile: ./dev/Dockerfile
          tag: 'latest'
      - run:
          name: Login to public Docker registry
          command: echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_LOGIN" --password-stdin
      - docker/push:
          digest-path: /tmp/digest.txt
          image: suculent/console-build-env
          tag: 'latest'

  vue-job:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - setup_remote_docker
      - docker/check
      - docker/build:
          docker-context: ./vue
          image: suculent/console-build-env
          dockerfile: ./vue/Dockerfile
          tag: 'vue'
      - run:
          name: Login to public Docker registry
          command: echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_LOGIN" --password-stdin
      - docker/push:
          digest-path: /tmp/digest.txt
          image: suculent/console-build-env
          tag: 'vue'

workflows:
  build-dev:
    jobs:
      - dev-job:
          context:
            - dockerhub

  build-vue:
    jobs:
      - vue-job:
          context:
            - dockerhub
